CREATE TABLE project
(
    id      BIGINT AUTO_INCREMENT NOT NULL,
    name    VARCHAR(255) NOT NULL,
    user_id BIGINT NULL,
    CONSTRAINT pk_project PRIMARY KEY (id)
);

CREATE TABLE user
(
    id    BIGINT AUTO_INCREMENT NOT NULL,
    name  VARCHAR(255) NOT NULL,
    email VARCHAR(255) NULL,
    CONSTRAINT pk_user PRIMARY KEY (id)
);

ALTER TABLE project
    ADD CONSTRAINT FK_PROJECT_ON_USER FOREIGN KEY (user_id) REFERENCES user (id);